name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * * # daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
  steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Install package and dependencies
    - name: Install
      run: |
        # Upgrade pip
        python -m pip install --upgrade pip
        # Install the package
        pip install --force-reinstall -e .
        # Development dependencies
        pip install --force-reinstall -r requirements.txt
        # Install additional GitHub actions build dependencies
        pip install tox-gh-actions setuptools wheel twine

    # Test with tox - uses tox-gh-actions to map build strategy matrix python-version with tox config.
    - name: Test with tox
      run: |
        tox
